name: ReVanced

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"
          
      - name: Download base APK
        run: chmod +x dl-ytb.sh

      - name: Download base APK
        run: ./dl-ytb.sh
